Lab02/Lab02/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encuesta/', include('encuesta.urls') ),
    path('operaciones/', include('operaciones.urls')),
    path('radiocilindro/',include('radiocilindro.urls'))
]

Lab02/encuesta/urls.py
from django.urls import  path

from . import views

app_name ='encuesta'

urlpatterns = [
path('',views.index,name='index'),
path('enviar', views.enviar, name='enviar'),
]

Lab02/operaciones/urls.py
from django.urls import  path

from . import views

app_name ='operaciones'

urlpatterns = [
    path('',views.index,name="index"),
    path('enviar/',views.enviar,name="enviar")
]

Lab02/radiocilindro/urls.py
from django.urls import path
from . import views

appname = 'ejercicios'

urlpatterns = [
    path('',views.index,name='index'),
    path('respuesta',views.respuesta,name='respuesta'),
]

Lab02/encuesta/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'titulo' : "Formulario",
    }
    return render(request, 'encuesta/formulario.html' , context)
def enviar(request):
    context = {
        'titulo' : "Respuesta",
        'nombre' : request.POST['nombre'],
        'clave' : request.POST['password'],
        'educacion' : request.POST['educacion'],
        'nacionalidad' : request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo' : request.POST['email'],
        'website' : request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)

Lab02/operaciones/views.py
from typing import ContextManager
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'formulario.html')
def enviar(request):
    num1 = request.POST['num1']
    num2 = request.POST['num2']
    operacion = request.POST['operacion']
    if operacion=='suma':
        resultado=int(num1)+int(num2)
    elif operacion=='resta':
        resultado=int(num1)-int(num2)
    elif operacion=='multiplicacion':
        resultado=int(num1)*int(num2)
    else:
        resultado=int(num1)/int(num2)
    context={
        'titulo': "Respuesta",
        'num1' : num1 ,
        'num2' : num2 ,
        'respuesta' : resultado,
        'operacion' : operacion,
    }
    return render(request,'respuesta.html',context)

Lab02/radiocilindro/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'formulario.html')

def respuesta(request):
    diametro = request.POST['diametro']
    altura =request.POST['altura']
    respuesta = 3.14159265358979323846*float(diametro)*float(altura)
    context={
       'resultado' :  respuesta ,
         'diametro': diametro,
       'altura' : altura
    }
    return  render(request,'respuesta.html',context)

Lab02/encuesta/templates/encuesta/formulario.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

    </head>
    <body>
        <h2>{{ titulo }}</h2>
        <form action="{% url 'encuesta:enviar' %}" method="post">
             {% csrf_token %}
            Nombre:
            <input type="text" name="nombre" maxlength="50"><br> 
            Contraseña:
            <input type="password" name="password"><br>                                                                                        
            Educacion:
            <select name="educacion">
                <option value="sin-estudios">Sin estudios</option>
                <option value="educacion-obligatoria">Educacion Obligatoria</option>
                <option value="formacion-profesional">Formacion Profesional</option>
                <option value="universidad">Universidad</option>
            </select> <br>
            Nacionalidad:
            <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
            <input type="radio" name="nacionalidad" value="otra">Otra</input><br>
            Idiomas:
            <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
            <input type="checkbox" name="idiomas" value="ingles">Ingles</input>
            <input type="checkbox" name="idiomas" value="frances">Frances</input>
            <input type="checkbox" name="idiomas" value="aleman">Aleman</input><br>
            Email:
            <input type="text" name="email"><br>
            Sitio Web:
            <input type="text" name="sitioweb"><br>
            <input type="submit" name="submit" value="Enviar">
        </form>
    </body>
</html>

Lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p> 
<p>Clave:{{ clave }}</p>
<p>Educacion: {{ educacion }}</p>
<p>Nacionalidad:{{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas%}
    <li>{{ item }}</li>
    {% endfor%}
</ul>
<p>Email: {{ correo }}</p>
<p>Siitio Web: {{website}}</p>

Lab02/operaciones/templates/formulario.html
<form action="{% url 'operaciones:enviar' %}" method="post">
{% csrf_token %}
  <p>numero 1<input type="text" name="num1" size="40"></p>
  <p>numero 2<input type="text" name="num2" size="40"></p>
  <p>Operacion a realizar
    <input type="radio" name="operacion" value="suma"> suma
    <input type="radio" name="operacion" value="resta"> resta
    <input type="radio" name="operacion" value="multiplicacion"> multiplicacion
    <input type="radio" name="operacion" value="division"> division
  </p>
  <p>
    <input type="submit" value="Enviar">
    <input type="reset" value="Borrar">
  </p>
</form>

Lab02/operaciones/templates/respuesta.html
  
<h1> {{ titulo }}</h1>
<p>La {{ operacion }} de {{num1}} y {{num2}} es {{ respuesta}}</p>

Lab02/radiocilindro/templates/formulario.html
<form action="{% url 'respuesta' %}" method="post">
{% csrf_token %}
  <p>Introduzca el diametro en metros<input type="text" name="diametro" size="40"></p>
  <p>Introduzca la altura en metros<input type="text" name="altura" size="40"></p>
  
  <p>
    <input type="submit" value="Enviar">
    <input type="reset" value="Borrar">
  </p>
</form>

Lab02/radiocilindro/templates/respuesta.html
el volumen del cilindro con altura: {{altura}}<br>
y altura:{{altura}}<br>
  es {{resultado}} metros cubicos